name: color_picker_example
description: Simple example of how to use the FlexColorPicker package.
version: 1.1.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flex_color_picker: ^1.1.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
