name: flex_color_picker
description: A customizable Flutter color picker.
version: 1.0.0-dev.2
homepage: https://github.com/rydmike/flex_color_picker

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
