name: color_picker
description: A highly customizable Flutter color picker.
version: 1.0.0
author: Mike Rydstrom

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
