name: flex_color_picker
description: A customizable Flutter primary, accent and custom color picker. Includes an optional HSV wheel color picker.
version: 2.6.0-dev.2
homepage: https://github.com/rydmike/flex_color_picker
repository: https://github.com/rydmike/flex_color_picker
issue_tracker: https://github.com/rydmike/flex_color_picker/issues
documentation: https://github.com/rydmike/flex_color_picker/blob/master/README.md

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.1.0-0.0.pre.2111'

dependencies:
  flutter:
    sdk: flutter

  # Color utilities by Google (material.io).
  # Used to compute and create Tonal Palette theme colors.
  #
  # Flutter SDK from 2.10.0 stable also uses and depends on this package.
  # Use ^0.1.3 for Flutter stable 2.10.x, that uses 0.1.3
  # Use ^0.1.3 for Flutter stable 3.0.x, that uses 0.1.4.
  # Use ^0.1.3 for Flutter rel candidates 3.1, 3.2, 3.4, that uses 0.1.5, beware that
  # version 0.1.5 has a new algo compared to 0.1.4 that changes some seed colors slightly.
  #
  # Use ^0.2.0 for Flutter master 3.1.0-x, that uses 0.2.0 after 5.8.2022 release.
  #
  # Here we use a controversial range since 0.2.0 is breaking over 0.1.x, but works for our case.
  # Older version 0.1.3 and 0.1.4 in theory also works, but they break some color values.
  material_color_utilities: '>=0.1.5 <=0.2.0'

dev_dependencies:
  collection:
  flutter_test:
    sdk: flutter
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/
